### ISSUE TITLE
When multiple users are using the same biobricks library there are ownership issues

### ISSUE THREAD

**Issue by tomlue** [biobricks-ai/biobricks#13]
```
yifan@wsl:~/molecular-vae$ python processTox21.py
fatal: detected dubious ownership in repository at '/mnt/ssd/biobricks/biobricks-ai/tox21/5c16c5012ef64298a947a857c190d50aabe45383'
To add an exception for this directory, call:
    git config --global --add safe.directory /mnt/ssd/biobricks/biobricks-ai/tox21/5c16c5012ef64298a947a857c190d50aabe45383
Traceback (most recent call last):
  File "/home/yifan/molecular-vae/processTox21.py", line 5, in <module>
    ns = bb.assets('tox21') # get the paths for the 'tox21' brick
  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yifan/.local/lib/python3.11/site-packages/biobricks/api.py", line 9, in assets
```

![image](https://github.com/biobricks-ai/biobricks/assets/1987278/e1bed33b-9459-47a5-aa08-b7da5aa0935c)

**Comment by tomlue** [comment]
fixed in 0.2.2
